//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Logger.h
//  @ Date : 2020/1/7
//  @ Author :
//
//

#if !defined(LOGGER_H)
#define LOGGER_H

#include "../commonmethod.h"
#include "../utilities_global.h"
#include "LoggerConfig.h"
#include "consoleoutputer.h"
#include "functional"
#include "logpublisher.h"
#include "logsaver.h"
#include <QDateTime>
#include <QQmlContext>
#include <QQmlEngine>
#include <QThread>

class UTILITIESSHARED_EXPORT Logger : public QObject
{
    Q_OBJECT

private:
    Logger();

public:
    static Logger *getIns()
    {
        static Logger instance;
        return &instance;
    }

    void setContextProperty(QQmlEngine &engine);

    void registerCategory(QLoggingCategory *category);

    static void qlogMessageHandler(QtMsgType msgType, const QMessageLogContext &context, const QString &msg);

    ~Logger() override;

signals:
    void newLog(QString category, int logLevel, QString msg);

private slots:
    void onLogLevelChanged(int logLevel);

private:
    void setLogEnable(QLoggingCategory *category, int logLevel);

    void setLogEnable(QLoggingCategory *category, QtMsgType qmsgType, int logLevel)
    {
        category->setEnabled(qmsgType, qmsgTypeToLevel[qmsgType] >= logLevel);
    }

private:
    LoggerConfig *loggerConfig = nullptr;
    ConfigFile *loggerConfigFile = nullptr;
    QList<QLoggingCategory *> logCategorys;
    QMap<QtMsgType, int> qmsgTypeToLevel;
    ConsoleOutputer consoleOutputer;
    LogSaver *logSaver;
    QThread saveLogThd;
    LogPublisher *logPublisher;
};

class CategoryRegister
{
public:
    CategoryRegister(QLoggingCategory &category)
    {
        Logger::getIns()->registerCategory(&category);
    }
};

#define SILICOOL_CREATE_LOGGING_CATEGORY(categoryGetterName, categoryName)                                                                           \
    QLoggingCategory &categoryGetterName()                                                                                                           \
    {                                                                                                                                                \
        static QLoggingCategory category(categoryName);                                                                                              \
        return category;                                                                                                                             \
    }                                                                                                                                                \
    static CategoryRegister categoryGetterName##___(categoryGetterName());

#define SILICOOL_DECLARE_LOGGING_CATEGORY(name, exportStatement) extern exportStatement QLoggingCategory &name();

#endif    // LOGGER_H
